name: neways3
description: A new Flutter project.

#publish_to: "none" # Remove this line if you wish to publish to pub.dev
#Last Play store version -> 1.0.7+10
version: 1.0.7+10

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: #^1.0.2
  flutter_svg: #^1.1.3
  google_fonts: #^3.0.1
  get: #^4.6.5
  lottie: #^1.4.1
  emoji_picker_flutter:
  socket_io_client: #^2.0.0
  image_picker: #^0.8.5+3
  dio:
  get_storage:
  hive: #^2.2.3
  hive_flutter: #^1.1.0
  path_provider: #^2.0.11
  flutter_easyloading: #^3.0.5
  cached_network_image: #^3.2.1
  intl: #^0.17.0
  month_year_picker: #^0.2.0+2
  timeago: #^3.3.0
  shimmer: #^2.0.0
  file_picker: #^5.2.2
  qr_flutter: #^4.0.0
  flutter_barcode_scanner: #^2.0.0
  permission_handler: ^10.4.2 #^10.2.0
  # open_file:
  better_open_file: ^3.6.4
  gallery_saver: #^2.3.2
  animated_text_kit: #^4.2.2
  # firebase & notification
  firebase_messaging: ^14.6.6 #^14.1.0
  firebase_core: #^2.2.0
  flutter_local_notifications: ^12.0.3+1
  drop_down_list:
  client_information: ^2.0.3+1
  flutter_switch: 
  url_launcher: 
  # material_design_icons_flutter: ^5.0.6996
  quick_actions: ^1.0.3
  
  # message
  flutter_speed_dial: ^3.0.5
  flutter_emoji: ">= 2.0.0"
  flutter_smart_dialog: ^4.9.0+6
  flutter_gif: ^0.0.4
  any_animated_button: ^0.0.4
  async_button_builder: ^3.0.0+1
  
  cloud_firestore:
  percent_indicator: ^4.2.3
  material_dialogs: ^1.1.4
  elastic_drawer: ^2.0.2
  scrollable_positioned_list: ^0.3.8
  fast_contacts: ^3.0.3
  chips_choice: ^3.0.0
  audioplayers: ^4.1.0
  flutter_ringtone_player: ^3.2.0
  flutter_animated_dialog: ^2.0.1
  html_unescape: ^2.0.0
  html: ^0.15.4
  flutter_staggered_animations: ^1.1.1
  #mentionable_text_field: ^0.0.2
  package_info_plus: ^4.1.0
  store_redirect: ^2.0.1
  contacts_service: ^0.6.3
  mentionable_text_field: ^0.0.2
  table_calendar: ^3.0.9
  location: ^5.0.3
  geocoding: ^2.1.0
  network_info_plus: ^4.0.2
  connectivity_plus: ^4.0.2
  wifi_scan: ^0.4.0+2
  app_settings: ^5.0.0
  wifi_iot: ^0.3.18+1

dev_dependencies:
  flutter_launcher_icons: #"^0.10.0"
  flutter_test:
    sdk: flutter

  flutter_lints: #^2.0.0
# Add Apps Launcher icon commend flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/audio/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
